# Documentacion en el Readme aprueba de weones, para el más tonto del equipo. Si eres arquitecto, usar categorías y como implementadas.
# Sirven los diagramas de flujo Mermaid, mientras sean entendibles no necesariamente tienen que ser estandarizados.

# Arquitectura, responsabilidad, propósito toma de dependencia, y cómo funciona el proyecto a grandes rasgos, separadas por carpetas;
# Módulos test, y modularización. Hoy se usa integración; siempre tener un módulo duplicado que te permita. 

# ModuleTest tiene el propósito de hacer una prueba unitaria; en ingeniería de software se usa ese concepto para cuando testeas una 
# métrica de la unidad con tal de ver si cumple su funcionalidad. Con tal de dejar una prueba automatizada con log y unitaria que no
# pasa por todo el proyecto para ver un error. 

# RUT nuevo: podría tener un script que me trae todos los chilenos, y si no encuentra uno chileno, me avisa en el console.log 

# BUSCAR CONCEPTO DE PRUEBA UNITARIA. SIEMPRE TENER UN ÚNICO INPUT Y UN ÚNICO OUTPUT.

# BUSCAR DESIGN PATTERNS Y USAR GEMINI PARA HACER DIAGRAMAS DE DESIGN PATTERNS; HACER REPO CON APRENDIZAJES DE DESIGN PATTERNS. 